### ISSUE TITLE
[Commenting functions]

### ISSUE THREAD

**Issue by ErikRowe** [vortexntnu/Vortex-CV#20]
**Time estimate:** 2 hours  
**Deadline:**  02.feb

**Description of task:**
Code needs commenting so others can understand what happens, when to call a function and so on

**Comment by theBadMusician** [comment]
The packages that are up for ASAP documentation: PointCloud Processing (Erik), PointCloud republishing (Jana), Feature Detection (BenG).

**Comment by ErikRowe** [comment]
added wrong pull request. but i fixed it
